name: Deployment

on:
  push:
    branches:
    - main

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python "3.11"
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install project
      run: poetry install
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & Publish
      run: |
        poetry version "${NEW_VERSION}"
        poetry build -f wheel
        poetry config pypi-token.pypi "${PYPI_TOKEN}"
        poetry publish
      shell: bash
      env:
        NEW_VERSION: ${{ steps.tag_version.outputs.new_version }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
