name: Pull Request Checks

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  pull-requests: read

jobs:
  validate-pr:
    name: Validate Pull Request Title
    runs-on: ubuntu-latest
    steps:
    - name: Validate Pull Request Title
      uses: amannn/action-semantic-pull-request@v5.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
